export async function POST(request) {
  try {
    const { to, subject, itinerary, trip } = await request.json();
    if (!to || !itinerary) return Response.json({ error: "Missing email or itinerary" }, { status: 400 });

    const RESEND_KEY = process.env.RESEND_API_KEY;
    if (!RESEND_KEY) return Response.json({ error: "Email not configured yet" }, { status: 500 });

    const htmlBody = `
      <div style="font-family: Georgia, serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="font-size: 22px; color: #111;">🗺️ Your Road Trip: ${trip.start} → ${trip.end}</h1>
        ${trip.depart ? `<p style="color: #6b7280; font-size: 14px;">Departing ${trip.depart}</p>` : ""}
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
        <div style="font-size: 14px; line-height: 1.8; color: #374151; white-space: pre-wrap;">${itinerary.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/^(Day \d+[^\n]*)/gm, '<h2 style="font-size:16px;color:#111;margin-top:24px;">$1</h2>')}</div>
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
        <p style="font-size: 12px; color: #9ca3af;">Generated by <a href="https://ourroadtripplanner.com" style="color: #2563eb;">ourroadtripplanner.com</a></p>
      </div>
    `;

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${RESEND_KEY}` },
      body: JSON.stringify({ from: "trips@ourroadtripplanner.com", to, subject, html: htmlBody }),
    });

    const data = await res.json();
    if (!res.ok) throw new Error(data.message || "Failed to send");
    return Response.json({ success: true });
  } catch (e) {
    return Response.json({ error: e.message }, { status: 500 });
  }
}
