export async function POST(request) {
  try {
    const { to, subject, itinerary, trip } = await request.json();
    if (!to || !itinerary) return Response.json({ error: "Missing email or itinerary" }, { status: 400 });

    const RESEND_KEY = process.env.RESEND_API_KEY;
    if (!RESEND_KEY) return Response.json({ error: "Email not configured yet" }, { status: 500 });

    const htmlBody = `
      <div style="font-family: Georgia, serif; max-width: 600px; margin: 0 auto; padding: 20px; background: #ffffff;">
        <div style="background: #2C2C2A; padding: 20px; border-radius: 8px; margin-bottom: 24px; text-align: center;">
          <h1 style="font-size: 22px; color: #F5F5F0; margin: 0;">🗺️ Your Road Trip Itinerary</h1>
          <p style="color: #D85A30; font-size: 13px; margin: 6px 0 0; letter-spacing: 0.1em;">EVERY ROAD · YOUR WAY</p>
        </div>
        <h2 style="font-size: 18px; color: #111;">${trip.start} → ${trip.end}</h2>
        ${trip.depart ? `<p style="color: #6b7280; font-size: 14px;">Departing ${trip.depart}</p>` : ""}
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
        <div style="font-size: 14px; line-height: 1.8; color: #374151;">
          ${itinerary
            .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
            .replace(/^#{1,3}\s*(Day\s+\d+[^\n]*)/gm, '<h2 style="font-size:16px;color:#fff;background:#2563eb;padding:8px 12px;border-radius:6px;margin-top:24px;">$1</h2>')
            .replace(/\n/g, '<br/>')
          }
        </div>
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
        <div style="text-align: center; padding: 16px; background: #f9fafb; border-radius: 8px;">
          <p style="font-size: 12px; color: #9ca3af; margin: 0;">Generated by <a href="https://ourroadtripplanner.com" style="color: #2563eb;">ourroadtripplanner.com</a></p>
          <p style="font-size: 11px; color: #d1d5db; margin: 4px 0 0;">AI-generated itinerary for planning purposes only. Always verify conditions before travel.</p>
        </div>
      </div>
    `;

    // Try sending from the verified domain first, fall back to onboarding address
    const fromAddresses = [
      "Our Road Trip Planner <trips@ourroadtripplanner.com>",
      "Our Road Trip Planner <onboarding@resend.dev>"
    ];

    let lastError = null;
    for (const from of fromAddresses) {
      const res = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${RESEND_KEY}` },
        body: JSON.stringify({ from, to, subject, html: htmlBody }),
      });
      const data = await res.json();
      if (res.ok) return Response.json({ success: true });
      lastError = data.message || "Failed to send";
    }
    throw new Error(lastError);
  } catch (e) {
    return Response.json({ error: e.message }, { status: 500 });
  }
}

