export default function Terms() {
  return (
    <main style={{ maxWidth: 700, margin: "0 auto", padding: "2rem 1rem", fontFamily: "Georgia, serif", color: "#374151", lineHeight: 1.8 }}>
      <h1 style={{ fontSize: 28, fontWeight: 700, color: "#111", marginBottom: "0.5rem" }}>Terms of Use</h1>
      <p style={{ fontSize: 13, color: "#9ca3af", fontFamily: "sans-serif", marginBottom: "2rem" }}>Last updated: May 2026</p>

      <p>Welcome to Our Road Trip Planner. By using this website, you agree to these Terms of Use. Please read them carefully.</p>

      <h2 style={{ fontSize: 18, fontWeight: 700, color: "#111", marginTop: "1.5rem" }}>1. Use of the Service</h2>
      <p>Our Road Trip Planner provides AI-generated road trip itineraries for informational and planning purposes only. You may use this service for personal, non-commercial trip planning. You agree not to misuse, copy, or redistribute the service or its outputs for commercial purposes without our written consent.</p>

      <h2 style={{ fontSize: 18, fontWeight: 700, color: "#111", marginTop: "1.5rem" }}>2. AI-Generated Content Disclaimer</h2>
      <p>All itineraries, suggestions, hotel recommendations, restaurant recommendations, activity ideas, driving times, historical marker information, and scenic route suggestions are generated by artificial intelligence. This content is provided for planning inspiration only and should not be relied upon as authoritative or accurate.</p>
      <p style={{ marginTop: "0.75rem" }}>You are solely responsible for verifying:</p>
      <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
        <li>Current road conditions and driving times</li>
        <li>Hotel availability and current pricing</li>
        <li>Restaurant hours and availability</li>
        <li>Attraction hours, admission fees, and closures</li>
        <li>Weather conditions along your route</li>
        <li>Any travel advisories or restrictions</li>
      </ul>

      <h2 style={{ fontSize: 18, fontWeight: 700, color: "#111", marginTop: "1.5rem" }}>3. Limitation of Liability</h2>
      <p>Our Road Trip Planner and its owners shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of, or reliance on, any itinerary or content generated by this service. This includes but is not limited to: missed reservations, travel delays, accidents, injuries, property damage, financial losses, or any other harm resulting from following AI-generated suggestions.</p>

      <h2 style={{ fontSize: 18, fontWeight: 700, color: "#111", marginTop: "1.5rem" }}>4. Blog and Editorial Content Disclaimer</h2>
      <p>Our Road Trip Planner publishes travel guides, road trip itineraries, and destination articles for informational and inspirational purposes only. While we make reasonable efforts to provide accurate and helpful content, we make no warranties regarding the accuracy, completeness, or currentness of any editorial content on this site.</p>
      <p style={{ marginTop: "0.75rem" }}>Travel conditions, business hours, road conditions, weather, and safety considerations change frequently. You are solely responsible for:</p>
      <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
        <li>Verifying that all businesses, attractions, and destinations mentioned are currently open and operating</li>
        <li>Assessing whether any suggested activities, routes, or destinations are appropriate for your physical condition, health, age, and abilities</li>
        <li>Checking current weather forecasts and any relevant safety advisories before travel</li>
        <li>Taking all necessary precautions when visiting locations that involve physical activity, extreme temperatures, remote areas, or other potential hazards</li>
        <li>Consulting appropriate medical professionals regarding any health-related travel considerations</li>
      </ul>
      <p style={{ marginTop: "0.75rem" }}>Our Road Trip Planner is not liable for any injury, illness, accident, loss, or damages of any kind arising from reliance on editorial content published on this site, including but not limited to blog posts, travel guides, and destination recommendations.</p>

      <h2 style={{ fontSize: 18, fontWeight: 700, color: "#111", marginTop: "1.5rem" }}>5. Affiliate Links</h2>
      <p>This site contains affiliate links to hotels, campgrounds, and other travel services. When you click these links and make a purchase or booking, we may earn a commission at no additional cost to you. See our full Affiliate Disclosure for details.</p>

      <h2 style={{ fontSize: 18, fontWeight: 700, color: "#111", marginTop: "1.5rem" }}>6. Privacy</h2>
      <p>Your use of this service is also governed by our Privacy Policy, which is incorporated into these Terms by reference.</p>

      <h2 style={{ fontSize: 18, fontWeight: 700, color: "#111", marginTop: "1.5rem" }}>7. Intellectual Property</h2>
      <p>The Our Road Trip Planner name, logo, and website design are the property of Our Road Trip Planner. The AI-generated itinerary content produced for your personal use may be used for personal trip planning purposes only.</p>

      <h2 style={{ fontSize: 18, fontWeight: 700, color: "#111", marginTop: "1.5rem" }}>8. Changes to These Terms</h2>
      <p>We reserve the right to update these Terms of Use at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>

      <h2 style={{ fontSize: 18, fontWeight: 700, color: "#111", marginTop: "1.5rem" }}>9. Contact</h2>
      <p>For questions about these terms, please contact us at <a href="mailto:hello@ourroadtripplanner.com" style={{ color: "#2563eb" }}>hello@ourroadtripplanner.com</a>.</p>

      <div style={{ marginTop: "2rem", paddingTop: "1rem", borderTop: "1px solid #e5e7eb", fontFamily: "sans-serif", fontSize: 12, color: "#9ca3af" }}>
        <a href="/" style={{ color: "#2563eb", textDecoration: "none" }}>← Back to Road Trip Planner</a>
      </div>
    </main>
  );
}
